### ISSUE TITLE
Update error to version cf711ac!!

### ISSUE THREAD

**Issue by Trzinka** [frlequ/home-assistant-network-tariff#10]
When upgrading to the cf711ac version, it reports an error:
Failed to perform the action update/install. The version cf711ac for this integration cannot be used with HACS.

**Comment by frlequ** [comment]
Currently HACS is not supported. Please do a manual upgrade.

**Comment by frlequ** [comment]
Fixed with: https://github.com/frlequ/home-assistant-network-tariff/pull/11
