### ISSUE TITLE
Another version of colours

### ISSUE THREAD

**Issue by trozman** [frlequ/home-assistant-network-tariff#13]
Firstly, thanks for this great integration!

My version of colours (which also goes well with a dark HA theme):

...
colorMap:
  "1": "#db4437ff"
  "2": "#ffa600ff"
  "3": "#fafa0dff"
  "4": "#0899f8ff"
  "5": "#43a047ff"
...

**Comment by frlequ** [comment]
Nice!

You probably ment the [card](https://github.com/frlequ/network-tariff-card) version, not the integration 😄

**Comment by trozman** [comment]
Oh, sorry, will move it there. You can delete it here.
