### ISSUE TITLE
Feature Request: Remove the need to modify configuration.yaml

### ISSUE THREAD

**Issue by devdems** [frlequ/home-assistant-network-tariff#4]
We should remove the need to modify configuration.yaml because it will be easier for deployment.

**Comment by frlequ** [comment]
It's much easier to deploy a `configuration.yaml` than the `config flow` for simple projects like this.

But sometime in the future, sure.

**Comment by DejanBukovec** [comment]
I vote for this...

**Comment by devdems** [comment]
Duplicate https://github.com/frlequ/home-assistant-network-tariff/issues/7

**Comment by frlequ** [comment]
##  Features

Added Config Flow. Now you don't need to write sensors in  `configuration.yaml` https://github.com/frlequ/home-assistant-network-tariff/pull/14

##  New Configuration & Upgrade

After installation, go to Settings -> Add Integration and search for Elektro Network Tariff.

> [!IMPORTANT]
> If you are upgrading from an older version, please **remove** platform sensor from `configuration.yaml`, you don't need it anymore.
>
>```yaml
>sensor:
>  - platform: elektro_network_tariff
>```
