### ISSUE TITLE
Feature Request: Add power that is set for each time block

### ISSUE THREAD

**Issue by devdems** [frlequ/home-assistant-network-tariff#5]
We should add an option that will enable the users to provide the power in W for all 5 time blocks. That would mean we need to introduce an additional sensor that will output the power (W) for the current time block.

**Comment by frlequ** [comment]
This should involve a seperate values (W) for each tariff block, and then display as sensor attributes as tariff changes?

I can add additional setup options via config.yaml,  where users can add/edit their W limits. 

I'm not sure if such values exist in moj elektro api... It would be great to make this some how semi-automatic.

**Comment by devdems** [comment]
Good point. As a matter of fact, we can get this on mojelektro API.

We can get this with GET https://api.informatika.si/mojelektro/v1/merilna-tocka/{gsrn}

This is a snippet of the response:

`{
    "dobavitelj": {
        "datumDo": "9999-12-31",
        "datumOd": "2011-01-01",
        "eic": "11XIGET--------D",
        "naziv": "GEN-I D.O.O.",
        "oznaka": 10021
    },
    "dogovorjeneMoci": [
        {
            "casovniBlok1": "0.0",
            "casovniBlok2": "0.0",
            "casovniBlok3": "0.0",
            "casovniBlok4": "0.0",
            "casovniBlok5": "0.0",
            "datumDo": "2024-12-31T00:00:00Z",
            "datumOd": "2024-01-01T00:00:00Z",
            "datumVnosa": "2023-06-11",
            "nacinDolocitve": "DISTRIBUTER",
            "novUporabnik": true,
            "oznakaIzracuna": "M1",
            "veljavnost": false
        },
        {
            "casovniBlok1": "7.2",
            "casovniBlok2": "8.1",
            "casovniBlok3": "8.1",
            "casovniBlok4": "8.1",
            "casovniBlok5": "8.1",
            "datumDo": "2024-12-31T00:00:00Z",
            "datumOd": "2024-01-01T00:00:00Z",
            "datumVnosa": "2023-07-06",
            "nacinDolocitve": "DISTRIBUTER",
            "novUporabnik": false,
            "oznakaIzracuna": "M1",
            "veljavnost": false
        },
        {
            "casovniBlok1": "7.4",
            "casovniBlok2": "8.1",
            "casovniBlok3": "8.1",
            "casovniBlok4": "8.1",
            "casovniBlok5": "8.1",
            "datumDo": "2024-12-31T00:00:00Z",
            "datumOd": "2024-01-01T00:00:00Z",
            "datumVnosa": "2023-07-24",
            "minimalnaMoc": "4.6",
            "nacinDolocitve": "DISTRIBUTER",
            "novUporabnik": false,
            "oznakaIzracuna": "M1",
            "prikljucnaMoc": "17.0",
            "veljavnost": true
        }
    ],
.
.
.
}
`
So we can parse casovniBlok1, casovniBlok2, casovniBlok3, casovniBlok4, casovniBlok5 where veljavnost = true

Is this something you can add to mojelektro plugin? Users would need to input also gsrn.

**Comment by frlequ** [comment]
> Is this something you can add to mojelektro plugin? Users would need to input also gsrn.

Yes, this should be part of Moj Elektro API component. Will take a look. 
Also the gsrn can be parsed with just meter_id, but it needs needs two requests.

**Comment by devdems** [comment]
> > Is this something you can add to mojelektro plugin? Users would need to input also gsrn.
> 
> Yes, this should be part of Moj Elektro API component. Will take a look. Also the gsrn can be parsed with just meter_id, but it needs needs two requests.

It can be yes, just bear in mind that users can have multiple gsrn's. I have two and only one has the block defined.

**Comment by frlequ** [comment]
I have one under `identifikator`  (GSRN MM)
and one under `merilneTocke` (GSRN MT)

Do yo have more than this two?

**Comment by devdems** [comment]
![image](https://github.com/frlequ/home-assistant-network-tariff/assets/8215353/233d222e-e1ee-42de-b95f-3bfdb1469bb1)

I have it like this and it works only on this one with the arrow.

**Comment by devdems** [comment]
Maybe vrsta = OMTO is the key but I'm not sure.

**Comment by frlequ** [comment]
Strange but yeah, i think OMTO is the key.

**Comment by dolenec** [comment]
power limit could be probably set also manually..

**Comment by devdems** [comment]
> power limit could be probably set also manually..

No need if we are going to get this from mojelektro.

**Comment by dolenec** [comment]
Do you have any timeline when it will be done?

**Comment by frlequ** [comment]
Use a template sensor in the meantime.

**Comment by andrejs2** [comment]
Is there any chance you (@devdems or @dolenec @frlequ ) share a template or sensor config for time blocks?
I just discovered this integration and trying to set thing up in HA...
Thanks for sharing and making this... 👍

**Comment by devdems** [comment]
You can just create new helper ->template -> template a sensor

put this code into the template and change your block power from 17000 to your liking.

{% if  states('sensor.elektro_network_tariff') == '1' %}{% set blok = 17000 %}
{% elif  states('sensor.elektro_network_tariff') == '2' %}{% set blok = 17000 %}
{% elif  states('sensor.elektro_network_tariff') == '3' %}{% set blok = 17000 %}
{% elif  states('sensor.elektro_network_tariff') == '4' %}{% set blok = 17000 %}
{% elif  states('sensor.elektro_network_tariff') == '5' %}{% set blok = 17000 %}
{% endif %}

{{ blok }}

**Comment by devdems** [comment]
Feature added to mojelektro plugin https://github.com/frlequ/homeassistant-mojelektro/pull/19
